#!/bin/sh
set -e

echo "Welcome to Sherwyn's Artix system-install script!"
echo 

[ "$EUID" -ne 0 ] && echo "Run this script as root" && exit

echo "=== Preferences ==="
read -p "Enter username: " username
read -p "Enter password: "   -s password
echo
read -p "Confirm password: " -s confirm_password
echo
[ "$password" != "$confirm_password" ] && echo "Passwords do not match" && exit

read -p "Enter hostname: " hostname
read -p "Enter install disk: " install_disk
echo

echo "=== Detecting legacy or UEFI... ==="
    if [ -d /sys/efi/firmware ] 
    then
        echo "UEFI detected"
        uefi=1
    else
        echo "Legacy boot detected"
        unset uefi
    fi
echo

echo "=== Partitioning disk ==="
    echo "Set ${install_disk}1 for swap"
    echo "Set ${install_disk}2 for root"
    echo "Set ${install_disk}3 for home"
    [ "${uefi+1}" ] && echo "Set ${install_disk}4 for uefi"
    read -p "Press enter to continue to cfdisk"
    cfdisk $install_disk
echo

echo "=== Formatting partitions ==="
    sleep 2
    mkfs.ext4 -L ROOT ${install_disk}2
    mkfs.ext4 -L HOME ${install_disk}3
    [ "${uefi+1}" ] && mkfs.fat -L EFI -F 32 ${install_disk}4 # only for UEFI
    mkswap -L SWAP ${install_disk}1
echo

echo "=== Mounting partitions ==="
    sleep 2
    swapon /dev/disk/by-label/SWAP
    mount /dev/disk/by-label/ROOT /mnt
    mkdir /mnt/home
    mount /dev/disk/by-label/HOME /mnt/home

    [ "${uefi+1}" ] && mkdir /mnt/boot 
    [ "${uefi+1}" ] && mount /dev/disk/by-label/EFI /mnt/boot/efi 
echo

echo "=== Installing base system and kernel ==="
    sleep 2
    basestrap /mnt base base-devel runit elogind-runit
    basestrap /mnt linux linux-firmware
echo

echo "=== Generating fstab ==="
    sleep 2
    fstabgen -U /mnt >> /mnt/etc/fstab
echo

echo "=== chrooting into system ==="
    sleep 2
    artix-chroot /mnt << CHROOT_COMMANDS

echo "=== Setting locales ==="
    sed 's/#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen > /etc/locale.gen
    sed 's/#ja_JP.UTF-8/ja_JP.UTF-8/' /etc/locale.gen > /etc/locale.gen
    locale-gen
echo

echo "=== Boot loader ==="
if [ "${uefi+1}" ] 
then 
    sleep 2
    pacman -S --noconfirm refind-efi
    refind-install
else
    pacman -S --noconfirm grub os-prober
    grub-install --recheck ${install_disk}
    grub-mkconfig -o /boot/grub.cfg
fi
echo

echo "=== Adding user ==="
    echo $password | passwd --stdin root
    useradd -m $username
    echo $password | passwd --stdin $username
echo

echo "=== Setting hostname ==="
    echo $hostname > /etc/hostname
echo

echo "=== Installing network tools ==="
    pacman -S --noconfirm dhcpcd wpa_supplicant
    pacman -S --noconfirm connman-runit connman-gtk connman
    ln -s /etc/runit/sv/connmand /run/runit/service
echo

echo "=== Installing X, terminal, and window manager ==="
    pacman -S --noconfirm xorg xorg-xinit termite i3 i3blocks
echo

echo "=== Exiting system ==="
    exit
CHROOT_COMMANDS
    umount -R /mnt
echo

echo "System install complete. Please reboot into system to continue."
    
